force-app/main/default/objects/Log_Event__e/Log_Event__e.object-meta.xml
<CustomObject>
    <description>Published by the Apex logger to create log records.</description>
    <label>Log Event</label>
    <pluralLabel>Log Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Log_Event__e/fields/Executing_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Executing_User_Id__c</fullName>
    <description>Captures the Id of the user under which the execution context is running.</description>
    <label>Executing User Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>A message stored for the log.</description>
    <label>Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <description>Used to indicate the severity level of the captured log record. This maps to the restricted Severity picklist within the Log__c object.</description>
    <label>Severity</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Logger_Configuration__mdt/Logger_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>Controls options available to configure the Apex logger class.</description>
    <label>Logger Configuration</label>
    <pluralLabel>Logger Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Logger_Configuration__mdt/fields/Enable_System_Debug__c.field-meta.xml
<CustomField>
    <fullName>Enable_System_Debug__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked, logs will also be published using the System.debug method.</description>
    <inlineHelpText>When checked, logs will also be published using the System.debug method.</inlineHelpText>
    <label>Enable System Debug</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Logger_Configuration__mdt/fields/Flush_Limit__c.field-meta.xml
<CustomField>
    <fullName>Flush_Limit__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Indicates the max amount of logs to be held within the Apex Logger before being published and flushed (I.e. cleared). A blank value or a value less than 1 results in immediate publishing of each log.</description>
    <inlineHelpText>Indicates the max amount of logs to be held within the Apex Logger before being published and flushed (I.e. cleared). A blank value or a value less than 1 results in immediate publishing of each log.</inlineHelpText>
    <label>Flush Limit</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Logger_Configuration__mdt/fields/Minimum_Severity__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Severity__c</fullName>
    <description>Logs will only be generated with a severity that is equal to or greater than the minimum selected level. Order from highest to lowest: ERROR, WARN, INFO, DEBUG.</description>
    <inlineHelpText>Logs will only be generated with a severity that is equal to or greater than the minimum selected level. Order from highest to lowest: ERROR, WARN, INFO, DEBUG.</inlineHelpText>
    <label>Minimum Severity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ERROR</fullName>
                <default>true</default>
                <label>ERROR</label>
            </value>
            <value>
                <fullName>WARN</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Logger_Configuration__mdt/fields/Pause_Logging__c.field-meta.xml
<CustomField>
    <fullName>Pause_Logging__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked, all Apex logger instances that reference this configuration will stop publishing log events.</description>
    <inlineHelpText>When checked, all Apex logger instances that reference this configuration will stop publishing log events.</inlineHelpText>
    <label>Pause Logging</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Logger.cls
public without sharing class Logger implements ILogger {
    private final Integer MAX_MESSAGE_LENGTH = 255;

    private final List<Log_Event__e> queuedLogs;
    private final Integer flushLimit;
    private final Severity minimumSeverity;
    private final Boolean enableSystemDebug;
    private final Boolean pauseLogging;

    public Logger() {
        this.queuedLogs = new List<Log_Event__e>();
        this.flushLimit = 1;
        this.minimumSeverity = Severity.ERROR;
        this.enableSystemDebug = false;
        this.pauseLogging = false;
    }
    
    public Logger(Logger_Configuration__mdt config) {
        if (config == null) {
            return;
        }
        
        this.queuedLogs = new List<Log_Event__e>();
        this.flushLimit = config.Flush_Limit__c != null ? Integer.valueOf(config.Flush_Limit__c) : 1;
        this.minimumSeverity = this.getSeverityFromText(config.Minimum_Severity__c);
        this.enableSystemDebug = config.Enable_System_Debug__c;
        this.pauseLogging = config.Pause_Logging__c;
    }

    public void error(String message) {
        addToLogQueue(Severity.ERROR, message, null);
    }

    public void error(String message, Object obj) {
        addToLogQueue(Severity.ERROR, message, obj);
    }

    public void warn(String message) {
        addToLogQueue(Severity.WARN, message, null);
    }

    public void warn(String message, Object obj) {
        addToLogQueue(Severity.WARN, message, obj);
    }

    public void info(String message) {
        addToLogQueue(Severity.INFO, message, null);
    }

    public void info(String message, Object obj) {
        addToLogQueue(Severity.INFO, message, obj);
    }

    public void debug(String message) {
        addToLogQueue(Severity.DEBUG, message, null);
    }

    public void debug(String message, Object obj) {
        addToLogQueue(Severity.DEBUG, message, obj);
    }

    @TestVisible
    private Severity getSeverityFromText(String severityText) {
        if (String.isBlank(severityText)) {
            return Severity.ERROR;
        }

        Severity configuredSeverity;
        switch on severityText {
            when 'ERROR' {
                configuredSeverity = Severity.ERROR;
            }	
            when 'WARN' {
                configuredSeverity = Severity.WARN;
            }
            when 'INFO' {
                configuredSeverity = Severity.INFO;
            }
            when 'DEBUG' {
                configuredSeverity = Severity.DEBUG;
            }
            when else {
                configuredSeverity = this.minimumSeverity;
            }
        }
        return configuredSeverity;
    }

    @TestVisible
    private void addToLogQueue(Severity logSeverity, String message, Object obj) {
        if (this.skipPublishingLog(logSeverity, message)) {
            return;
        }

        Log_Event__e log = new Log_Event__e(
            Message__c = message.length() > this.MAX_MESSAGE_LENGTH ? message.substring(0, this.MAX_MESSAGE_LENGTH - 1) : message,
            Severity__c = logSeverity.name(),
            Executing_User_Id__c = UserInfo.getUserId()
        );
        this.setRequestContextValues(log);
        this.setObjectValues(log, obj);
        this.publishAndFlush(log);
    }

    @TestVisible
    private Boolean skipPublishingLog(Severity logSeverity, String message) {
        Boolean skipPublishing = false;
        if (logSeverity.ordinal() < this.minimumSeverity.ordinal() || this.pauseLogging || String.isBlank(message)) {
            skipPublishing = true;
        }
        return skipPublishing;
    }

    @TestVisible
    private void setRequestContextValues(Log_Event__e log) {

    }

    @TestVisible
    private void setObjectValues(Log_Event__e log, Object obj) {
        
    }

    @TestVisible
    private void publishAndFlush(Log_Event__e log) {
        this.queuedLogs.add(log);
        if (this.flushLimit <= 1 || this.queuedLogs.size() >= this.flushLimit) {
            EventBus.publish(this.queuedLogs);
            this.queuedLogs.clear();
        }
    }

    private enum Severity { DEBUG, INFO, WARN, ERROR }
}