force-app/main/default/objects/Trigger_Action_Configuration__c/Trigger_Action_Configuration__c.object-meta.xml
<CustomObject>
    <description>Defines what actions can be run within various trigger contexts.</description>
    <label>Trigger Action Configuration</label>
    <nameField>
        <label>Trigger Action Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Action Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trigger_Action_Configuration__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <description>The API name of the class that contains logic to be executed within the target trigger.</description>
    <inlineHelpText>The API name of the class that contains logic to be executed within the target trigger.</inlineHelpText>
    <label>Class Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger_Action_Configuration__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enables the configuration to executed for its target trigger.</description>
    <inlineHelpText>Enables the configuration to executed for its target trigger.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Action_Configuration__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Determines the order in which the configuration will be executed compared to other configurations. A lower number indicates a higher priority.</description>
    <inlineHelpText>Determines the order in which the configuration will be executed compared to other configurations. A lower number indicates a higher priority.</inlineHelpText>
    <label>Priority</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trigger_Action_Configuration__c/fields/Target_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Target_Trigger__c</fullName>
    <description>The configuration will be executed for the specified API name of the target trigger.</description>
    <inlineHelpText>The configuration will be executed for the specified API name of the target trigger.</inlineHelpText>
    <label>Target Trigger</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TriggerActionDispatcher.cls
public with sharing class TriggerActionDispatcher {
    // TODO: Determine what static variables to be set and reused
    // across transactions/execution contexts

    public static void execute(String targetTriggerApiName) {
        if (!Trigger.isExecuting) return;

        Trigger_Action_Configuration__c[] actions = getTriggerConfigurations(targetTriggerApiName);
        Set<String> classNames = new Set<String>();
        for (Trigger_Action_Configuration__c action: actions) {
            classNames.add(action.Class_Name__c);
        }

        ApexTypeImplementor[] apexClasses = getApexClasses(classNames, getCurrentContextInterface());
    }

    private static Trigger_Action_Configuration__c[] getTriggerConfigurations(String targetTriggerApiName) {
        return [SELECT Class_Name__c 
                FROM Trigger_Action_Configuration__c
                WHERE Is_Active__c = true
                    AND Target_Trigger__c = :targetTriggerApiName
                    AND Class_Name__c != null
                ORDER BY Priority__c ASC NULLS FIRST];
    }

    private static ApexTypeImplementor[] getApexClasses(Set<String> classNames, String triggerContextInterface) {
        return [SELECT ClassName, ClassNamespacePrefix
                FROM ApexTypeImplementor 
                WHERE InterfaceName =: triggerContextInterface 
                    AND IsConcrete = true];
    }
    
    private static String getCurrentContextInterface() {
        System.TriggerOperation opsType = Trigger.operationType;
        String interfaceName;
        switch on opsType {
            when BEFORE_INSERT {

            }	
            when BEFORE_UPDATE {

            }
            when BEFORE_DELETE {

            }
            when AFTER_INSERT {

            }
            when AFTER_UPDATE {

            }
            when AFTER_DELETE {

            }
            when AFTER_UNDELETE {

            }
        }
        return interfaceName;
    }
 }