force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>A custom object used capture log records generated within various execution contexts, such as Apex.</description>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{0}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <description>The error message of a thrown exception.</description>
    <inlineHelpText>The error message of a thrown exception.</inlineHelpText>
    <label>Exception Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Exception_Name__c.field-meta.xml
<CustomField>
    <fullName>Exception_Name__c</fullName>
    <description>The name of a thrown exception within Apex.</description>
    <inlineHelpText>The name of a thrown exception within Apex.</inlineHelpText>
    <label>Exception Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Executing_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Executing_User_Id__c</fullName>
    <description>Captures the Id of the user under which the execution context is running.</description>
    <inlineHelpText>Captures the Id of the user under which the execution context is running.</inlineHelpText>
    <label>Executing User Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <description>The line number from which an exception was thrown within Apex.</description>
    <inlineHelpText>The line number from which an exception was thrown within Apex.</inlineHelpText>
    <label>Line Number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>A message stored for the log.</description>
    <inlineHelpText>A message stored for the log.</inlineHelpText>
    <label>Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Object_Data__c.field-meta.xml
<CustomField>
    <fullName>Object_Data__c</fullName>
    <description>The JSON serialized object data from a log.</description>
    <inlineHelpText>The JSON serialized object data from a log.</inlineHelpText>
    <label>Object Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <description>Used to indicate the severity level of the captured log record.</description>
    <inlineHelpText>Used to indicate the severity level of the captured log record.</inlineHelpText>
    <label>Severity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>WARN</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>FATAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>The stack trace captured from an exception thrown within Apex.</description>
    <inlineHelpText>The stack trace captured from an exception thrown within Apex.</inlineHelpText>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <description>Captures the unique request Id generated for each execution context or transaction within Apex (sourced from Request class).</description>
    <inlineHelpText>Captures the unique request Id generated for each execution context or transaction within Apex (sourced from Request class).</inlineHelpText>
    <label>Transaction Id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <description>Captures the Apex execution type (called Quiddity). Sourced from the Quiddity value of the Request class.</description>
    <inlineHelpText>Captures the Apex execution type (called Quiddity). Sourced from the Quiddity value of the Request class.</inlineHelpText>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ANONYMOUS</fullName>
            </value>
            <value>
                <fullName>AURA</fullName>
            </value>
            <value>
                <fullName>BATCH_ACS</fullName>
            </value>
            <value>
                <fullName>BATCH_APEX</fullName>
            </value>
            <value>
                <fullName>BATCH_CHUNK_PARALLEL</fullName>
            </value>
            <value>
                <fullName>BATCH_CHUNK_SERIAL</fullName>
            </value>
            <value>
                <fullName>BULK_API</fullName>
            </value>
            <value>
                <fullName>COMMERCE_INTEGRATION</fullName>
            </value>
            <value>
                <fullName>DISCOVERABLE_LOGIN</fullName>
            </value>
            <value>
                <fullName>EXTERNAL_SERVICE_CALLBACK</fullName>
            </value>
            <value>
                <fullName>FUNCTION_CALLBACK</fullName>
            </value>
            <value>
                <fullName>FUTURE</fullName>
            </value>
            <value>
                <fullName>INBOUND_EMAIL_SERVICE</fullName>
            </value>
            <value>
                <fullName>INVOCABLE_ACTION</fullName>
            </value>
            <value>
                <fullName>PLATFORM_EVENT_PUBLISH_CALLBACK</fullName>
            </value>
            <value>
                <fullName>POST_INSTALL_SCRIPT</fullName>
            </value>
            <value>
                <fullName>QUEUEABLE</fullName>
            </value>
            <value>
                <fullName>QUICK_ACTION</fullName>
            </value>
            <value>
                <fullName>REMOTE_ACTION</fullName>
            </value>
            <value>
                <fullName>REST</fullName>
            </value>
            <value>
                <fullName>RUNTEST_ASYNC</fullName>
            </value>
            <value>
                <fullName>RUNTEST_DEPLOY</fullName>
            </value>
            <value>
                <fullName>RUNTEST_SYNC</fullName>
            </value>
            <value>
                <fullName>SCHEDULED</fullName>
            </value>
            <value>
                <fullName>SOAP</fullName>
            </value>
            <value>
                <fullName>SYNCHRONOUS</fullName>
            </value>
            <value>
                <fullName>TRANSACTION_FINALIZER_QUEUEABLE</fullName>
            </value>
            <value>
                <fullName>VF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/fields/Transaction_Type_Short_Code__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type_Short_Code__c</fullName>
    <description>The short code value of a transaction type (sourced from Quiddity).</description>
    <inlineHelpText>The short code value of a transaction type (sourced from Quiddity).</inlineHelpText>
    <label>Transaction Type Short Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LogEventTriggerHandler.cls
public with sharing class LogEventTriggerHandler implements ISObjectAfterInsert {
    public void handleAfterInsert(SObject[] newRecords, Map<Id, SObject> newRecordsMap) {
        List<Log__c> logs = new List<Log__c>();
        for (SObject logEvent : newRecords) {
            Log__c log = new Log__c(
                Severity__c = (String)logEvent.get('Severity__c'),
                Executing_User_Id__c = (String)logEvent.get('Executing_User_Id__c'),
                Message__c = (String)logEvent.get('Message__c'),
                Transaction_Id__c = (String)logEvent.get('Transaction_Id__c'),
                Transaction_Type__c = (String)logEvent.get('Transaction_Type__c'),
                Transaction_Type_Short_Code__c = (String)logEvent.get('Transaction_Type_Short_Code__c'),
                Object_Data__c = (String)logEvent.get('Object_Data__c'),
                Exception_Name__c = (String)logEvent.get('Exception_Name__c'),
                Line_Number__c = (Integer)logEvent.get('Line_Number__c'),
                Exception_Message__c = (String)logEvent.get('Exception_Message__c'),
                Stack_Trace__c = (String)logEvent.get('Stack_Trace__c')
            );
            logs.add(log);
        }

        if (logs.size() > 0) {
            INSERT logs;
        }
    }
}